### ISSUE TITLE
Footer display hard to read

### ISSUE THREAD

**Issue by pbstudent** [BCcampus/pressbooks-textbook#106]
Upgrading to Pressbooks book 1.10.0 theme and Pressbooks-textbook.3.1.1
resulted in the following book footer:
![creative clinical teaching in the health professions clinical teaching open textbook](https://user-images.githubusercontent.com/24277755/29653974-9c1a082e-88ab-11e7-9e28-8365cb8c0b44.png)

**Comment by bdolor** [comment]
I agree, it's a bit much...pulls attention away from the actual book. I gather this was an intentional decision to add `pb_custom_copyright` notice to the footer and observe the same behaviour regardless of theme. https://github.com/pressbooks/pressbooks-book/commit/9da6aa462c70d09a837e469c9533dd0a0ea3347d 

Will see if there is something in the open textbook theme that will minimize the visual impact. In the meantime, you may consider getting rid of the blockquotes in 'Copyright Notice' at `Book Information` 
![image](https://user-images.githubusercontent.com/2048170/29669566-c0764e02-8898-11e7-92ea-04b727355122.png)

**Comment by pbstudent** [comment]
Thanks will remove quotes.
