### ISSUE TITLE
Can't find hypothesis plugin in opentextbc and pressbooks.bccampus instances

### ISSUE THREAD

**Issue by josieg** [BCcampus/pressbooks-textbook#177]
### Description 

I received a request from Lucas to turn on hypothesis in one of his books, but the hypothesis plugin and settings seem to be missing from both Pressbooks instances in both admin and superadmin views. 

Was this done intentionally? If so, why? Or is this some sort of glitch? If so, can we get this fixed?

**Expected behaviour** 

I want to be able to enable hypothesis as an admin and super admin in Pressbooks. 

**Actual behaviour** 

I can't find the hypothesis plugin anywhere in Pressbooks in order to enable it in a book. 

### Steps to reproduce the problem

n/a

### System Information

- Textbooks for Pressbooks: 4.2.0
- Pressbooks: 5.4.5
- WordPress: 4.9.7

**Comment by bdolor** [comment]
Hypothesis was removed as a bundled plugin in the last release because it was necessary to remove responsibility for updating a third party plugin  https://github.com/BCcampus/pressbooks-textbook/releases/tag/4.2.0 

It has been resolved by installing the hypothesis plugin separately on those instances. 

Closing.
