### ISSUE TITLE
Process for migration of features to Pressbooks core

### ISSUE THREAD

**Issue by greatislander** [BCcampus/pressbooks-textbook#25]
We are looking into starting to migrate some features from Pressbooks Textbook into the core Pressbooks plugin so as to make them available to all users of Pressbooks. First and foremost is the MCE Table Editor (https://github.com/pressbooks/pressbooks/issues/154) and the MCE Superscript and Subscript buttons (https://github.com/pressbooks/pressbooks/issues/157). I have introduced a couple of commits into pressbooks/dev that bring the MCE Table Editor plugin into Pressbooks core—however, it causes an error when the current version of Pressbooks Textbook is installed and the Open Textbook theme is active. How would you like to coordinate this? I can submit a pull request which removes the table editor from Pressbooks Textbook, and then going forward as I migrate features from Textbook I can submit pull requests to handle the switch similarly. At this point the MCE Table Editor and the superscript and subscript buttons are the two features we are looking to move over. Thanks in advance for your thoughts on this. (FYI, @hughmcguire.)

**Comment by hughmcguire** [comment]
hi @bdolor ... i've got a client waiting for this ... could you take a look asap? thanks!

**Comment by bdolor** [comment]
I'm curious what error it causes — we both appear to be doing checks to see if it's already installed before it's activated. Nevertheless, since table editor is now a part of PB I will accept a PR that removes table editor from PBT, no problem.

Even better, if you are coordinating the switch with an update to the version number of PB, then a conditional check for that version or greater could be put in front of modifying the values in the array [here](https://github.com/BCcampus/pressbooks-textbook/blob/dev/pressbooks-textbook.php#L122) or [here](https://github.com/BCcampus/pressbooks-textbook/blob/dev/pressbooks-textbook.php#L156). At a later date, I can remove the mce-table-buttons plugin entirely from the `symbionts` directory.
