### ISSUE TITLE
Captions not in sync

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-textbook#33]
PressBooks v.2.5.2
PressBooks Textbook v.1.2.13

Captions in Image editor remain when removed from Media Library image caption.  In addition, adding captions in Media Library does not update captions of images already added to webpage.
![captions in image details](https://cloud.githubusercontent.com/assets/360534/8761980/ae1034a8-2d28-11e5-8a6d-9c809c6f18c7.png)

**Comment by bdolor** [comment]
Not a PBT issue — this is functionality specific to WP and as far as I know is expected WP behaviour. A default caption can be set in the media library so that when you add that image to a post, it will come with that default caption. If you want to override that default caption, you can do so by editing the image (and caption) inside the post. Editing the caption in the media library is not intended to be synced with each corresponding media image on every individual post after that media image has been added to the post, rather it is only to set a default caption.
