### ISSUE TITLE
PBT error on update

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-textbook#48]
Wordpress 4.3.1
Pressbooks 2.7.2
Pressbooks Textbook 1.2.16

![newver](https://cloud.githubusercontent.com/assets/360534/11951711/6ded29e4-a893-11e5-8aed-082503222893.png)

Updating to 2.0 creates the following error:
"PBT cannot find a Pressbooks install."

Resolutions?

**Comment by bdolor** [comment]
What was the order that the plugins were updated, PB first, or PBT first? 

I usually update WP, then PB, then PBT.

**Comment by sswettenham** [comment]
Order of install
1. Wordpress 4.3.1
2. Pressbooks 2.7.2
3. Pressbooks Textbook 1.2.16

Then tried to update PBT to version 2.
Currently unable to update PB beyond current version due to lower PHP server, the WP plugin list indicates no further update to PB available.  However, PBT indicates an update available.

**Comment by bdolor** [comment]
Ah, that explains it - you can't update PB until you update PHP. Are you able to put in the `wp-config.php` work around for a lower version of PHP so that you can update PB? `$pb_minimum_php = "5.4.0”;`

If you are on a RHEL OS where back porting PHP versions will take care of some of the security issues that you might encounter, this might be a way forward. 

Resolution: put in the $pb_minimum_php work around, update WP to 4.4, update PB to 3.1.1, update PBT to 2.1

**Comment by sswettenham** [comment]
We tried PHP workaround but it created to many strange errors so we backed off and stayed with existing versions until server can be upgraded to latest PHP in the new year.

Tried installing version PBT 2.1 onto existing existing configuration but still have same error:
"PBT cannot find a Pressbooks install."

I recommend that there be a warning on version compatibility for updates, and the installation instructions need to include details on order of updating as you have described - WP, then PB, then PBT.

Thanks
