### ISSUE TITLE
new pressbooks root theme

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-textbook#72]
Investigate if a root (child) theme can now be registered outside of PB core. If so, significant changes to the root theme have been made as of 3.9.5 and will need to be modified to reflect, at minimum, more books than is currently permitted. 

https://github.com/pressbooks/pressbooks/blob/dev/themes-root/pressbooks-publisher/templates/content.php#L3

**Comment by greatislander** [comment]
Hi @bdolor, Pressbooks 3.9.6 makes all book themes available in books and all non-book themes available to the root site whether they are in Pressbooks core or not. So that's a yes to the first question (see https://github.com/pressbooks/pressbooks/pull/525).

As to the other point, I will add a filter to that query vars array so that the defaults may be customized.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-textbook/commit/613b427178499b603f162f0b8ae3e5d26bec763e 

Thanks @greatislander for adding the filter to `WP_Site_Query`
