### ISSUE TITLE
Equation not showing

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/pressbooks-textbook#77]
Error with Math in HTML Web Version and PDF
https://opentextbc.ca/introtourism/chapter/chapter-4-food-and-beverage-services/

![screen shot 2017-01-16 at 8 48 11 am](https://cloud.githubusercontent.com/assets/23705492/21992218/7554d414-dbca-11e6-9ebb-f1e6eae327e4.png)

**Comment by bdolor** [comment]
I don't believe this is an equation. The text is `...reviewed with the cost symbols of three or four dollar signs: $$$ $$$$` 

Since the shortcode for equations is a double dollar sign, it is treating this line as an equation which generates the false flag/error. 

At any rate, it needs to be solved at the content level.
